let getShows = function(){
  return [
    { id: 'goodlife', name: 'The Good life', description: "Sitcom following two happily married couples living in London's suburbs. As his 40th birthday approaches, Tom Good decides to throw in the daily grind of the commute, office life and the career rat-race and attempt a self-sufficiency lifestyle with wife Barbara: they'll grow their own fruit and vegetables, keep a few animals, and make their own way in the world. Their best friends and next-door neighbours, Margot and Jerry Leadbetter, are shocked by the notion of their genteel neighbourhood being overrun by pigs, mud and other such unsophisticated muck. Jerry simply thinks Tom's gone mad, but Margot is outraged by the imposition. Can Tom and Barbara survive? Perhaps with a little of the neighbours' help..." },
    { id: 'bottom', name: 'Bottom', description: "Richie Richard and Eddie Hitler are the two most idiotic, depraved men in London. Living together in a disgusting, run down flat in Hammersmith, the pair are simultaneously best friends and worst enemies, regularly arguing, taking great joy in the pain of the other, and engaging in horrendous physical violence. Unemployed, incompetent, socially retarded and - in Richie's case - virginal, the pair engage in a never-ending cycle of clashes with each other, locals, fate, nature, time..." },
    { id: 'fawltytowers', name: 'Fawlty Towers', description: "Fawlty Towers, a 22-room hotel located in Torquay, the centre of the 'English Riviera', is a den of mishap and disaster. Basil Fawlty, owner and manager of the hotel, is a man of infinite capability in impoliteness, caustic intolerance and general rudeness toward the guests he views as an unwelcome imposition. His wife, Sybil, is of a more practical demeanour, but seems to have an immunity to work. The running of the hotel is thus often left to waitress, maid, and all-round help Polly. Meanwhilse, Spanish waiter and porter Manuel is still struggling with English." },
    { id: 'yesminister', name: 'Yes, Minister', description: "Jim Hacker, Member of Parliament, is appointed to the Cabinet as Minister For Administrative Affairs. There he is introduced to Bernard Woolley, his Principal Private Secretary, and the Civil Service's head of the deparment, Permanent Secretary Humphrey Appleby. Once ensconced in his ministry, Hacker is forced to fight Appleby, not to mention the Whitehall machine at large, at every turn in order to get his own way - and soon finds that manifesto promises are far harder to keep than anyone might have guessed." },
    { id: 'onlyfools', name: 'Only Fools and Horses', description: "Sitcom about of two streetwise south-Londoners: Derek 'Del Boy' Trotter and the younger brother he raised since their mother's death, Rodney. Through the initial series, the brothers shared their high-rise council flat in Nelson Mandela House with their Grandad. When he died his estranged brother, WWII Navy veteran Uncle Albert, moved in. In later series, Rodney married Cassandra and moved out to live with her, whilst Del began dating one-time magician's assistant Raquel, who eventually moved into the flat; in due course they were joined by a son, Damien." },
    { id: 'blackadder', name: 'Blackadder', description: "Like a stain on the eiderdown of English history, the Blackadder family has been present at some of the greatest events in our nation's past. We join their tale in the late 1400s, with Edmund Plantagenat, alias 'The Black Adder', the weasley 'spare' son of King Richard IV. En route to the dawn of the new millennium in 2000, we bump into Lords and Sirs of the dynasty including those from the times of King Charles I, Prince George in Regency England, the Captain Blackadder of World War I, and Elizabeth I's favourite Lord." }
  ];
}

module.exports = getShows;
